"""Applying new migrations

Revision ID: 6c7ecaebc2f6
Revises: 
Create Date: 2024-08-21 13:35:56.974953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7ecaebc2f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cca3', sa.String(length=3), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('capital', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('subregion', sa.String(length=100), nullable=False),
    sa.Column('area', sa.BigInteger(), nullable=False),
    sa.Column('map_url', sa.String(length=255), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('flag_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_neighbours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('neighbour_country_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['neighbour_country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_neighbours')
    op.drop_table('countries')
    # ### end Alembic commands ###
